FROM node:22-alpine

WORKDIR /usr/src/app

RUN apt-get update -y && apt-get install -y openssl

ARG DATABASE_URL

COPY ./package.json ./package.json
COPY ./turbo.json ./turbo.json

RUN npm install --verbose

COPY ./apps/user-app ./apps/user-app
COPY ./packages ./packages
COPY . .

RUN npm run db:generate
RUN DATABASE_URL=${DATABASE_URL} npx turbo build --filter=user-app...

EXPOSE 3001

CMD ["npm","run","start:fe"]

