FROM node:22-alpine

WORKDIR /usr/src/app

RUN apt-get update -y && apt-get install -y openssl


COPY ./package.json ./package.json
COPY ./turbo.json ./turbo.json

RUN npm install --verbose

COPY ./apps/axis-Bank ./apps/axis-Bank
COPY ./packages ./packages
COPY . .

RUN npm run db:generate

EXPOSE 3004

CMD ["npm","run","start:axis"]
