FROM node:22-alpine

WORKDIR /usr/src/app

COPY ./package.json ./package.json
COPY ./turbo.json ./turbo.json

COPY ./packages ./packages

RUN npm install --verbose

COPY ./apps/axis-Bank ./apps/axis-Bank
COPY . .

RUN npm run db:generate

EXPOSE 3004

CMD ["npm","run","start:axis"]
