FROM node:22-alpine

WORKDIR /usr/src/app

RUN apt-get update -y && apt-get install -y openssl


COPY ./package.json ./package.json
COPY ./turbo.json ./turbo.json

RUN npm install --verbose

COPY ./apps/bank-webhook ./apps/bank-webhook
COPY ./packages ./packages
COPY . .

RUN npm run db:generate

EXPOSE 3003

CMD ["npm","run","start:wh"]



