FROM node:22-alpine

WORKDIR /usr/src/app


COPY ./package.json ./package.json
COPY ./turbo.json ./turbo.json


COPY ./packages ./packages

RUN npm install --verbose

COPY ./apps/bank-webhook ./apps/bank-webhook
COPY . .

RUN npm run db:generate

EXPOSE 3003

CMD ["npm","run","start:wh"]



